name: interview
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  flutter_markdown: ^0.7.1
  dio: ^5.4.3+1
  logger: ^2.3.0
  shared_preferences: ^2.2.3
  flutter_slidable: ^3.1.0

dev_dependencies: 
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

flutter_launcher_icons: 
  android: launcher_icon
  image_path: assets/images/logo.webp
  web: 
    image_path: assets/images/logo.webp
    background_color: '#hexcode'
    theme_color: '#hexcode'
    generate: true
  windows: 
    image_path: assets/images/logo.webp
    generate: true
    icon_size: 48
  macos: 
    image_path: assets/images/logo.webp
    generate: true
  ios: true
  min_sdk_android: 21

